name: Build & Publish Base Image

on:
  workflow_dispatch:

jobs:
  Build_Base_Image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Ali-ACR
        uses: aliyun/acr-login@v1
        with:
          region-id: cn-hangzhou
          access-key-id: "${{ secrets.ACR_ACCESSKEYID }}"
          access-key-secret: "${{ secrets.ACR_ACCESSKEYSECRET }}"
          
      - name: Test Ali-ACR
        run: |
          docker pull ubuntu:20.04
          docker tag ubuntu:20.04 "registry.cn-hangzhou.aliyuncs.com/byrio/overleaf:test"
          docker push registry.cn-hangzhou.aliyuncs.com/byrio/overleaf:test
